# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clusteridv2b.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFindMatches = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindMatches.setGeometry(QtCore.QRect(450, 435, 261, 23))
        self.btnFindMatches.setObjectName("btnFindMatches")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 410, 191, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 355, 101, 31))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(469, 352, 91, 20))
        self.label.setObjectName("label")
        self.filterClusterSeries = QtWidgets.QLineEdit(self.centralwidget)
        self.filterClusterSeries.setGeometry(QtCore.QRect(160, 390, 121, 21))
        self.filterClusterSeries.setObjectName("filterClusterSeries")
        self.btnFindClusterSeries = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindClusterSeries.setGeometry(QtCore.QRect(60, 434, 241, 23))
        self.btnFindClusterSeries.setObjectName("btnFindClusterSeries")
        self.maxAtomsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.maxAtomsLineEdit.setGeometry(QtCore.QRect(240, 360, 41, 21))
        self.maxAtomsLineEdit.setObjectName("maxAtomsLineEdit")
        self.targetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.targetLineEdit.setGeometry(QtCore.QRect(590, 351, 121, 21))
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.toleranceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.toleranceLineEdit.setGeometry(QtCore.QRect(670, 410, 41, 21))
        self.toleranceLineEdit.setObjectName("toleranceLineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 390, 41, 20))
        self.label_4.setObjectName("label_4")
        self.matchOutput = QtWidgets.QTableWidget(self.centralwidget)
        self.matchOutput.setGeometry(QtCore.QRect(360, 466, 431, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.matchOutput.setFont(font)
        self.matchOutput.setColumnCount(4)
        self.matchOutput.setObjectName("matchOutput")
        self.matchOutput.setRowCount(0)
        self.matchOutput.horizontalHeader().setVisible(True)
        self.matchOutput.horizontalHeader().setCascadingSectionResizes(False)
        self.matchOutput.verticalHeader().setVisible(False)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 6, 781, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.filterMatched = QtWidgets.QLineEdit(self.centralwidget)
        self.filterMatched.setGeometry(QtCore.QRect(590, 380, 121, 21))
        self.filterMatched.setObjectName("filterMatched")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 380, 41, 20))
        self.label_7.setObjectName("label_7")
        self.seriesOutput = QtWidgets.QTableWidget(self.centralwidget)
        self.seriesOutput.setGeometry(QtCore.QRect(5, 466, 341, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.seriesOutput.setFont(font)
        self.seriesOutput.setColumnCount(3)
        self.seriesOutput.setObjectName("seriesOutput")
        self.seriesOutput.setRowCount(0)
        self.seriesOutput.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFindMatches.setText(_translate("MainWindow", "Find Matches"))
        self.label_5.setText(_translate("MainWindow", "Absolute Tolerance (amu):"))
        self.label_6.setText(_translate("MainWindow", "Max Atoms:"))
        self.label.setText(_translate("MainWindow", "Target Mass:"))
        self.btnFindClusterSeries.setText(_translate("MainWindow", "Find Cluster Series"))
        self.label_4.setText(_translate("MainWindow", "Filter:"))
        self.matchOutput.setSortingEnabled(True)
        self.label_7.setText(_translate("MainWindow", "Filter:"))
        self.seriesOutput.setSortingEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

