# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clusterid.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFindMatches = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindMatches.setGeometry(QtCore.QRect(450, 499, 261, 23))
        self.btnFindMatches.setObjectName("btnFindMatches")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 474, 191, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 436, 101, 31))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(469, 416, 91, 20))
        self.label.setObjectName("label")
        self.filterClusterSeries = QtWidgets.QLineEdit(self.centralwidget)
        self.filterClusterSeries.setGeometry(QtCore.QRect(160, 471, 121, 21))
        self.filterClusterSeries.setObjectName("filterClusterSeries")
        self.btnFindClusterSeries = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindClusterSeries.setGeometry(QtCore.QRect(50, 498, 251, 23))
        self.btnFindClusterSeries.setObjectName("btnFindClusterSeries")
        self.maxAtomsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.maxAtomsLineEdit.setGeometry(QtCore.QRect(240, 441, 41, 21))
        self.maxAtomsLineEdit.setObjectName("maxAtomsLineEdit")
        self.targetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.targetLineEdit.setGeometry(QtCore.QRect(590, 415, 121, 21))
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.toleranceLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.toleranceLineEdit.setGeometry(QtCore.QRect(670, 474, 41, 21))
        self.toleranceLineEdit.setObjectName("toleranceLineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 470, 41, 20))
        self.label_4.setObjectName("label_4")
        self.matchOutput = QtWidgets.QTableWidget(self.centralwidget)
        self.matchOutput.setGeometry(QtCore.QRect(360, 530, 431, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.matchOutput.setFont(font)
        self.matchOutput.setColumnCount(4)
        self.matchOutput.setObjectName("matchOutput")
        self.matchOutput.setRowCount(0)
        self.matchOutput.horizontalHeader().setVisible(True)
        self.matchOutput.horizontalHeader().setCascadingSectionResizes(False)
        self.matchOutput.verticalHeader().setVisible(False)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.filterMatched = QtWidgets.QLineEdit(self.centralwidget)
        self.filterMatched.setGeometry(QtCore.QRect(590, 444, 121, 21))
        self.filterMatched.setObjectName("filterMatched")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 444, 41, 20))
        self.label_7.setObjectName("label_7")
        self.seriesOutput = QtWidgets.QTableWidget(self.centralwidget)
        self.seriesOutput.setGeometry(QtCore.QRect(5, 530, 341, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.seriesOutput.setFont(font)
        self.seriesOutput.setColumnCount(3)
        self.seriesOutput.setObjectName("seriesOutput")
        self.seriesOutput.setRowCount(0)
        self.seriesOutput.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 350, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 400, 511, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 350, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 420, 511, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 370, 111, 20))
        self.label_10.setObjectName("label_10")
        self.formulaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.formulaLineEdit.setGeometry(QtCore.QRect(160, 370, 81, 21))
        self.formulaLineEdit.setObjectName("formulaLineEdit")
        self.formulaMassLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.formulaMassLineEdit.setGeometry(QtCore.QRect(290, 370, 61, 21))
        self.formulaMassLineEdit.setReadOnly(False)
        self.formulaMassLineEdit.setObjectName("formulaMassLineEdit")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(250, 370, 41, 20))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFindMatches.setText(_translate("MainWindow", "Find Matches"))
        self.label_5.setText(_translate("MainWindow", "Absolute Tolerance (amu):"))
        self.label_6.setText(_translate("MainWindow", "Max Atoms:"))
        self.label.setText(_translate("MainWindow", "Target Mass:"))
        self.btnFindClusterSeries.setText(_translate("MainWindow", "Find Cluster Series"))
        self.label_4.setText(_translate("MainWindow", "Filter:"))
        self.matchOutput.setSortingEnabled(True)
        self.label_7.setText(_translate("MainWindow", "Filter:"))
        self.seriesOutput.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Step 2: Which Charged Species Has A Mass of X?"))
        self.label_3.setText(_translate("MainWindow", "Step 4: What is the Mass of All Combinations of Selected Elements?"))
        self.label_8.setText(_translate("MainWindow", "Step 3: What is the Mass of the Following Formula?"))
        self.label_9.setText(_translate("MainWindow", "(e.g. VxOy, where x and y equal 0 to \"Max Atoms\")"))
        self.label_10.setText(_translate("MainWindow", "Chemical Formula:"))
        self.label_11.setText(_translate("MainWindow", "Mass:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

